[package]
name = "remote_client"
version = "0.1.0"
edition = "2021"

[lib]
name = "remote_client"
crate-type = ["cdylib", "rlib"]

[dependencies]
client = { path = "../client", version = "0.1.0" }
wasm-bindgen = "0.2.87"
