[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
name = "client"
crate-type = ["cdylib", "rlib"]

[dependencies]
macroquad = "0.4.2"
hex2d = "1.1.0"
itertools = "0.11.0"
serde_json = "1.0.91"
server = { path = "../server", version = "0.1.0" }
