version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directories:
      - client
      - server
    schedule:
      interval: daily


