[env]
RUST_BACKTRACE = '1'
RUSTFLAGS = '-Dwarnings' # Make sure CI fails on all warnings, including Clippy lints
CARGO_TERM_COLOR = 'always'

[tasks.random-actions]
description = "Run random actions tests"
run = 'cargo test --package server --test random_actions test_random_actions -- --exact --nocapture'
dir = "server"

[tasks.profile-random-actions]
description = "Run AI random actions test with profiling"
run = ["cargo test --release --features profiling --package server --test random_actions test_random_actions -- --exact --nocapture"]
dir = "server"

[tasks.test]
description = "Run server tests"
run = 'cargo nextest run {{arg(name="test", default="")}}'
dir = "server"

[tasks.update-tests]
description = "Run server tests and update JSON files"
run = 'cargo nextest run {{arg(name="test", default="")}}'
env = { UPDATE_EXPECTED = "true" }
dir = "server"

[tasks.server-format-and-lint]
description = "Format and lint all code"
run = [
    "cargo fmt",
    "cargo clippy --fix --allow-dirty --allow-staged"
]
dir = "server"

[tasks.client-format-and-lint]
description = "Format and lint all code"
run = [
    "cargo fmt",
    "cargo clippy --fix --allow-dirty --allow-staged"
]
dir = "client"

[tasks.format-and-lint]
depends = ["server-format-and-lint", "client-format-and-lint"]

[tasks.ci-server]
description = "Run CI tasks server"
dir = "server"
run = [
    "cargo build",
    "cargo fmt --check",
    "cargo clippy",
    "cargo nextest run"
]

[tasks.ci-client]
description = "Run CI tasks server"
dir = "client"
run = [
    "cargo build",
    "cargo fmt --check",
    "cargo clippy",
]

[tasks.profile]
description = "Run AI client with profiling"
run = ["cargo run --release --package client --features profiling --bin local_client -- ai"]
dir = "client"

[tools]
"cargo:cargo-nextest" = "latest"
rust = { version = "latest", components = "clippy,rustfmt" }

