[tasks.update-tests]
description = "Run server tests and update json files"
run = 'cargo test {{arg(name="test", default="")}}'
env = { UPDATE_EXPECTED = "true" }
dir = "server"

[tasks.server-format-and-lint]
description = "Format and lint all code"
run = [
    "cargo fmt",
    "cargo clippy --fix --allow-dirty --allow-staged"
]
dir = "server"

[tasks.client-format-and-lint]
description = "Format and lint all code"
run = [
    "cargo fmt",
    "cargo clippy --fix --allow-dirty --allow-staged"
]
dir = "client"

[tasks.format-and-lint]
depends = ["server-format-and-lint", "client-format-and-lint"]

[tools]
rust = "latest"

