[env]
RUST_BACKTRACE = '1'

[tasks.random-actions]
description = "Run server tests"
run = 'cargo nextest run --nocapture test_random_actions -Pbench'
dir = "server"

[tasks.test]
description = "Run server tests"
run = 'cargo nextest run {{arg(name="test", default="")}}'
dir = "server"

[tasks.update-tests]
description = "Run server tests and update JSON files"
run = 'cargo nextest run {{arg(name="test", default="")}}'
env = { UPDATE_EXPECTED = "true" }
dir = "server"

[tasks.server-format-and-lint]
description = "Format and lint all code"
run = [
    "cargo fmt",
    "cargo clippy --fix --allow-dirty --allow-staged"
]
dir = "server"

[tasks.client-format-and-lint]
description = "Format and lint all code"
run = [
    "cargo fmt",
    "cargo clippy --fix --allow-dirty --allow-staged"
]
dir = "client"

[tasks.format-and-lint]
depends = ["server-format-and-lint", "client-format-and-lint"]

[tasks.profile]
description = "Run AI client with profiling"
run = ["cargo run --release --package client --features profiling --bin local_client -- ai"]
dir = "client"

[tasks.profile-random-actions]
description = "Run AI random actions test with profiling"
run = ["cargo test --release --features profiling random_actions"]
dir = "server"

[tools]
"cargo:cargo-nextest" = "latest"
rust = { version = "latest", components = "clippy,rustfmt" }

