<script lang="ts">
  import {
    Archive,
    Lightbulb,
    Coins,
    Mountain,
    Trees,
    Wheat,
    Landmark,
    Castle,
    Building2,
    Smile,
    GraduationCap,
    Telescope,
    Store,
    Anchor,
    Ship,
    Sailboat,
    Compass,
    Footprints,
    Swords,
    Shield,
    ShieldCheck,
    ShieldAlert,
    Flag,
    Crown,
    Sword,
    Trophy,
    Flame,
    Target,
    BookOpen,
    Network,
    ScrollText,
    Drama,
    Hammer,
    Globe,
    Tent,
    Users,
    UserPlus,
    Handshake,
    Gem,
    Route,
    Fence,
    Frown,
    Sparkles,
    Package,
    Triangle,
  } from 'lucide-svelte';
  import obelisk from '../../client/assets/obelisk-svgrepo-com.png';
  import horse from '../../client/assets/horse-head-svgrepo-com.png';
  import elephant from '../../client/assets/elephant-svgrepo-com.png';
  const glyphs: Record<string, string> = {
    Legacy: obelisk,
    'Horse Power': horse,
    'Ivory Tower': elephant,
    Trample: elephant,
  };
  let { name }: { name: string } = $props();
  // Each objective has a stable visual identity; unknown future objectives get a target.
  const art: Record<string, { icon: typeof Target; accent: typeof Target }> = {
    'Optimized Storage': { icon: Archive, accent: Wheat },
    'Eureka!': { icon: Lightbulb, accent: Sparkles },
    Wealth: { icon: Coins, accent: Crown },
    'Ore Supplies': { icon: Mountain, accent: Package },
    'Wood Supplies': { icon: Trees, accent: Package },
    'Food Supplies': { icon: Wheat, accent: Package },
    'Large Civilization': { icon: Globe, accent: Building2 },
    'Advanced Culture': { icon: Drama, accent: Landmark },
    'Happy Population': { icon: Smile, accent: Users },
    Architecture: { icon: Hammer, accent: Castle },
    Consulate: { icon: Handshake, accent: Landmark },
    Metropolis: { icon: Building2, accent: Crown },
    Expansionist: { icon: Flag, accent: Globe },
    'Culture Power': { icon: Drama, accent: Crown },
    'Scientific Lead': { icon: GraduationCap, accent: Crown },
    'Coastal Culture': { icon: Anchor, accent: Landmark },
    'Religious Fervor': { icon: Landmark, accent: Sparkles },
    Fortifications: { icon: Castle, accent: Shield },
    'Star Gazers': { icon: Telescope, accent: Sparkles },
    Traders: { icon: Store, accent: Coins },
    Legacy: { icon: Landmark, accent: Crown },
    'City Planner': { icon: Building2, accent: Hammer },
    'Education Lead': { icon: BookOpen, accent: GraduationCap },
    Militarized: { icon: Swords, accent: BookOpen },
    'Culture Focus': { icon: Drama, accent: Target },
    'Science Focus': { icon: Lightbulb, accent: Target },
    'Trade Focus': { icon: Store, accent: Target },
    Seafarers: { icon: Sailboat, accent: Compass },
    Government: { icon: ScrollText, accent: Crown },
    'Goal Focused': { icon: Target, accent: BookOpen },
    'Diversified Research': { icon: Network, accent: Lightbulb },
    'High Culture': { icon: Drama, accent: Sparkles },
    'Sea Blockade': { icon: Ship, accent: Fence },
    'Large Fleet': { icon: Ship, accent: Crown },
    'Large Army': { icon: Users, accent: Swords },
    'Standing Army': { icon: Shield, accent: Building2 },
    Colony: { icon: Tent, accent: Globe },
    Threat: { icon: ShieldAlert, accent: Flag },
    Outpost: { icon: Tent, accent: Shield },
    Migration: { icon: Footprints, accent: Users },
    'Military Might': { icon: Swords, accent: Crown },
    'Trade Power': { icon: Store, accent: Crown },
    'Shipping Routes': { icon: Route, accent: Ship },
    'Horse Power': { icon: Flag, accent: Swords },
    'Ivory Tower': { icon: Gem, accent: Shield },
    Versatility: { icon: Network, accent: Users },
    Draft: { icon: UserPlus, accent: Shield },
    'City Founder': { icon: Hammer, accent: Flag },
    'Terror Regime': { icon: Frown, accent: Crown },
    'Magnificent Culture': { icon: Landmark, accent: Crown },
    Conqueror: { icon: Flag, accent: Castle },
    Warmonger: { icon: Flame, accent: Swords },
    General: { icon: Crown, accent: Shield },
    'Great Battle': { icon: Swords, accent: Trophy },
    Defiance: { icon: ShieldCheck, accent: Flag },
    'Naval Assault': { icon: Ship, accent: Sword },
    Bold: { icon: Sword, accent: Sparkles },
    'Legendary Battle': { icon: Trophy, accent: Crown },
    Scavenger: { icon: Package, accent: Sword },
    Aggressor: { icon: Sword, accent: Flag },
    'Barbarian Conquest': { icon: Flag, accent: Tent },
    Resistance: { icon: ShieldCheck, accent: Castle },
    'Great Commander': { icon: Crown, accent: Swords },
    Brutus: { icon: Sword, accent: Crown },
    Trample: { icon: Footprints, accent: Shield },
    'Sea Cleansing': { icon: Anchor, accent: ShieldCheck },
  };
  let choice = $derived(art[name] ?? { icon: Target, accent: Triangle });
  let Icon = $derived(choice.icon);
  let Accent = $derived(choice.accent);
</script>

<span class="objective-art" aria-hidden="true"
  >{#if glyphs[name]}<span class="objective-glyph" style={`mask-image:url("${glyphs[name]}")`}
    ></span>{:else}<Icon size={34} strokeWidth={1.35} />{/if}<span class="objective-art-accent"
    ><Accent size={15} strokeWidth={1.7} /></span
  ></span
>
