import {
  Wheat,
  Warehouse,
  Droplets,
  Beef,
  Pickaxe,
  Hammer,
  HeartPulse,
  Route,
  Fish,
  Ship,
  Shield,
  Map,
  BookOpen,
  School,
  GraduationCap,
  Brain,
  Swords,
  Castle,
  Anvil,
  Users,
  Sun,
  Flame,
  Church,
  Landmark,
  Handshake,
  Coins,
  Palette,
  Dumbbell,
  Drama,
  Calculator,
  Telescope,
  Vote,
  Scale,
  Heart,
  Store,
  Flag,
  Crown,
  Shovel,
  Scroll,
  ShieldCheck,
  Sparkles,
  Zap,
} from 'lucide-svelte';
import type { PublicAdvance } from './types';

// Short reading aids; the engine's complete rule text remains available on selection.
const advances = {
  Farming: [Wheat, 'Collect food from grassland and wood from forests.'],
  Storage: [Warehouse, 'Food storage increases from 2 to 7.'],
  Irrigation: [Droplets, 'Collect food from barren land. Ignore famine.'],
  Husbandry: [Beef, 'Collect from one land tile 2 spaces away; two with Roads. Once per turn.'],
  Mining: [Pickaxe, 'Collect ore from mountains.'],
  Engineering: [Hammer, 'Draw a wonder card. Build wonders in happy cities.'],
  Sanitation: [HeartPulse, 'Recruit 1 settler for 1 mood. Ignore pestilence and epidemics.'],
  Roads: [
    Route,
    'From/to cities, pay 1 food + 1 ore for +1 land range and ignore terrain. No exploring or boarding ships.',
  ],
  Fishing: [Fish, 'Collect food from one sea tile.'],
  Navigation: [Ship, 'Sail around the edge to the next sea area. Stop at unexplored regions.'],
  WarShips: [Shield, 'Ignore the first hit in round 1 when attacking by ship or disembarking.'],
  Cartography: [Map, 'Ship movement earns 1 idea; using Navigation also earns 1 culture.'],
  Writing: [BookOpen, 'Draw an action card and an objective card.'],
  PublicEducation: [School, 'Gain 1 idea when collecting in an Academy city. Once per turn.'],
  FreeEducation: [
    GraduationCap,
    'After buying an advance with gold or ideas, trade 1 extra idea for 1 mood.',
  ],
  Philosophy: [Brain, 'Gain 1 idea now, and 1 for each Science advance.'],
  Tactics: [Swords, 'Move army units and use the tactics on action cards.'],
  Siegecraft: [Castle, 'Cancel a Fortress’s extra die for 2 wood, or its hit protection for 2 ore.'],
  SteelWeapons: [
    Anvil,
    'Land battles: pay 1 ore for +2 combat value (+1 versus Steel Weapons). Free with Metallurgy against enemies without Steel Weapons.',
  ],
  Draft: [Users, 'Recruit an infantry unit with 1 mood instead of resources.'],
  Myths: [Sun, 'Spend mood to prevent event-driven city mood loss, except Pirates.'],
  Rituals: [Flame, 'Use resources instead of mood when increasing happiness.'],
  Priesthood: [Church, 'One Science advance per turn costs no resources. Still uses an action.'],
  StateReligion: [Landmark, 'Build a Temple without paying food. Once per turn.'],
  Bartering: [Handshake, 'Discard an action card for 1 gold or culture. Free, once per turn.'],
  TradeRoutes: [Route, 'Settlers and ships near non-angry enemy cities earn up to 4 food per turn.'],
  Taxes: [Coins, 'Spend an action and 1 mood for food, wood or ore equal to your city count. Once per turn.'],
  Currency: [Coins, 'Take gold instead of food from Trade Routes and Taxes.'],
  Arts: [Palette, 'Spend 1 culture for a free influence attempt. Once per turn.'],
  Sports: [Dumbbell, 'Spend an action and 1–2 culture to raise a city’s mood 1–2 steps.'],
  Monuments: [Landmark, 'Draw a wonder card. Wonder cities cannot be culturally influenced.'],
  Theaters: [Drama, 'Swap 1 mood and 1 culture either way. Free, once per turn.'],
  Math: [Calculator, 'Engineering and Roads cost no food.'],
  Astronomy: [Telescope, 'Navigation and Cartography cost no food.'],
  Medicine: [HeartPulse, 'Recover one resource spent after recruiting.'],
  Metallurgy: [
    Anvil,
    'Steel Weapons costs no ore against enemies without Steel Weapons. When collecting 2+ ore, replace 1 ore with 1 gold.',
  ],
  Voting: [Vote, 'Spend 1 mood to take a free Increase Happiness action.'],
  SeparationOfPower: [Scale, 'Culture tokens cannot boost influence attempts against your happy cities.'],
  CivilLiberties: [Heart, 'Gain 3 mood for an action. Draft now costs 2 mood per infantry.'],
  FreeEconomy: [Store, 'Spend 1 mood to collect without an action. Your only collection that turn.'],
  Nationalism: [Flag, 'Recruit an army or ship unit to gain 1 mood or culture.'],
  Totalitarianism: [Shield, 'Culture tokens cannot boost influence against cities with armies.'],
  AbsolutePower: [Crown, 'Buy an extra action for 2 mood. Once per turn.'],
  ForcedLabor: [Shovel, 'Spend 1 mood to treat angry cities as neutral this turn. Free, once per turn.'],
  Dogma: [Scroll, 'New Temples grant a free Theocracy advance. Idea storage drops to 2.'],
  Devotion: [ShieldCheck, 'Culture tokens cannot boost influence against your Temple cities.'],
  Conversion: [Sparkles, '+1 to influence rolls. Successful attempts earn 1 culture.'],
  Fanaticism: [Zap, '+2 in the first battle round at a Temple city. Gain infantry if you lose.'],
} as const;

const civilizationIcons: Record<string, typeof Wheat> = {
  Aqueduct: Droplets,
  RomanRoads: Route,
  Captivi: Swords,
  Provinces: Flag,
  Study: BookOpen,
  Sparta: Shield,
  HellenisticCulture: Palette,
  CityStates: Landmark,
  RiceCultivation: Wheat,
  Expansion: Map,
  Fireworks: Sparkles,
  ImperialArmy: Swords,
  ShipConstruction: Hammer,
  Longships: Ship,
  Raiding: Swords,
  RuneStones: Scroll,
  Canals: Droplets,
  CodeOfLaws: Scale,
  StarCatalogues: Telescope,
  Ziggurats: Church,
  IndianElephants: Shield,
  Proselytism: Users,
  Prosperity: Handshake,
  PeaceAndPoetry: Scroll,
};

export const groupIcons: Record<string, typeof Wheat> = {
  Agriculture: Wheat,
  Construction: Hammer,
  Seafaring: Ship,
  Education: GraduationCap,
  Warfare: Swords,
  Spirituality: Sun,
  Economy: Coins,
  Culture: Palette,
  Science: Telescope,
  Democracy: Vote,
  Autocracy: Crown,
  Theocracy: Church,
};
export function researchPresentation(advance: Pick<PublicAdvance, 'id' | 'group' | 'description'>) {
  const entry = advances[advance.id as keyof typeof advances];
  return {
    icon: entry?.[0] ?? civilizationIcons[advance.id] ?? groupIcons[advance.group] ?? BookOpen,
    summary:
      advance.id === 'Philosophy' && advance.description.includes('3 ideas')
        ? advance.description
        : (entry?.[1] ?? advance.description),
  };
}
