[package]
name = "server"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "git@github.com:boardgamers/clash.git"
homepage = "https://www.boardgamers.space/"
description = "A server for Clash of Cultures"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "server"
crate-type = ["cdylib", "rlib"]

[dependencies]
hex2d = "1.1.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
wasm-bindgen = "0.2.95"
async-std = "1.12.0"
wasm-bindgen-futures = "0.4.44"
serde-wasm-bindgen = "0.6.0"
itertools = "0.13.0"
quad-rand = "0.2.2"
console_error_panic_hook = "0.1.7"
