[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "server"
crate-type = ["lib"]

[dependencies]
hex2d = "1.1.0"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.83"
async-std = "1.12.0"
wasm-bindgen-futures = "0.4.33"
itertools = "0.13.0"
