name: Check Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
        experimental: 'true' # to get lock file support
    - name: Check all
      run: mise run ci-client
