name: Check Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
        experimental: 'true' # to get lock file support
      env:
        MISE_DISABLE_TOOLS: cargo:wasm-pack,cargo:wasm-bindgen-cli
    - name: Check all
      run: mise run ci-server
