name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build server
      working-directory: ./server
      run: cargo build --verbose
    - name: Run tests server
      working-directory: ./server
      run: cargo test --verbose
    #- name: Run clippy client
    #  working-directory: ./server
    #  run: cargo clippy
    # - name: Format client
    #  working-directory: ./server
    #   run: cargo fmt
    - name: Build client
      working-directory: ./client
      run: cargo build --verbose
    - name: Run tests client
      working-directory: ./client
      run: cargo test --verbose
    #- name: Run clippy client
    #  working-directory: ./client
    #  run: cargo clippy
    # - name: Format client
    #  working-directory: ./client
    #   run: cargo fmt
