name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
        version: 1.0
    - name: Install Cargo Audit
      run: cargo install cargo-audit
    - name: Build server
      working-directory: ./server
      run: cargo build
    - name: Run tests server
      working-directory: ./server
      run: cargo test
    - name: Run clippy client
      working-directory: ./server
      run: cargo clippy
    - name: Format client
      working-directory: ./server
      run: cargo fmt --check
    - name: Run cargo audit server
      working-directory: ./server
      run: cargo audit
    - name: Build client
      working-directory: ./client
      run: cargo build
    - name: Run tests client
      working-directory: ./client
      run: cargo test
    - name: Run clippy client
      working-directory: ./client
      run: cargo clippy
    - name: Format client
      working-directory: ./client
      run: cargo fmt --check
    - name: Run cargo audit client
      working-directory: ./client
      run: cargo audit
